"""
SafeCampus — Cyberbullying & Suicide Prevention Reporting Portal
Review 3 — Fine-tuned multilingual DistilBERT

Run:
    pip install streamlit transformers torch lime contractions emoji
    streamlit run safecampus_app.py

models/distilbert_finetuned/ must exist (generated by the fine-tuning notebook).
Falls back to martin-ha/toxic-comment-model if local model not found.
"""

import os, re, json, time
from datetime import datetime

import streamlit as st
import numpy as np

import nltk
nltk.download("stopwords", quiet=True)
nltk.download("wordnet",   quiet=True)
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer

import emoji as emoji_lib
import contractions

st.set_page_config(
    page_title="SafeCampus — Cyberbullying & Anti-Ragging Portal",
    page_icon="🛡️",
    layout="centered",
)

# ── NLP helpers ──────────────────────────────────────────────────────────────
_stop       = set(stopwords.words("english"))
_lemmatizer = WordNetLemmatizer()

def _expand_contractions(text):
    try:    return contractions.fix(text)
    except: return text

def _correct_elongated(text):
    return re.sub(r"(\w)\1{2,}", r"\1", text)

def clean_text(s: str) -> str:
    """Light clean — keeps Hindi/Hinglish words intact for mDistilBERT."""
    s = emoji_lib.replace_emoji(str(s), replace=" ")
    s = _expand_contractions(s)
    s = re.sub(r"http\S+",  " ", s)
    s = re.sub(r"@\w+",     " ", s)
    s = re.sub(r"#",        " ", s)
    s = _correct_elongated(s)
    s = re.sub(r"\s+", " ", s).strip()
    return s[:512]

# ── Severity lexicon ─────────────────────────────────────────────────────────
TIER1_INSULT = {
    "stupid","idiot","loser","dumb","ugly","fat","moron",
    "useless","pathetic","trash","scum","hate you","freak",
    "bakwas","bewakoof","gandu","chutiya","harami",
}
TIER2_THREAT = {
    "kill you","beat you","hurt you","destroy you",
    "fight you","i will find you","watch your back","make you pay",
    "maar dunga","peetunga","tod dunga",
}
TIER_RAGGING_MILD = {
    "fresher","junior","intro de","intro","sir bol",
    "dance kar","gaana ga","canteen se","senior ka order",
    "ragging","hierarchy",
}
TIER_RAGGING_SEVERE = {
    "hostel room aaja","murga","kapde nikal","strip",
    "mms","police","principal","maar","peet","baap",
    "will complain","teri shikayat","nude",
}
TIER3_SELF_HARM = {
    "kill myself","end it all","want to die","suicide","suicidal",
    "no reason to live","cant go on","better off dead",
    "end my life","not worth living","disappear forever",
    "everyone hates me","nobody cares","worthless","no point living",
    "jeena nahi","marna chahta","khatam karna",
}

def severity_score(text: str, model_prob: float) -> float:
    s = str(text).lower()
    score = 0.5 * model_prob
    if any(w in s for w in TIER1_INSULT)       : score += 0.15
    if any(w in s for w in TIER2_THREAT)       : score += 0.25
    if any(w in s for w in TIER_RAGGING_MILD)  : score += 0.15
    if any(w in s for w in TIER_RAGGING_SEVERE): score += 0.35
    if any(p in s for p in TIER3_SELF_HARM)    : score += 0.50
    return round(min(score, 1.0), 4)

def get_flags(text: str) -> list:
    s, flags = str(text).lower(), []
    if any(w in s for w in TIER1_INSULT)       : flags.append("Insult / Harassment")
    if any(w in s for w in TIER2_THREAT)       : flags.append("Direct Threat")
    if any(w in s for w in TIER_RAGGING_MILD)  : flags.append("Academic / Hierarchy Abuse")
    if any(w in s for w in TIER_RAGGING_SEVERE): flags.append("Severe Ragging / Hazing")
    if any(p in s for p in TIER3_SELF_HARM)    : flags.append("Suicide / Self-harm Risk")
    return flags or ["None detected"]

# ── Model loader ──────────────────────────────────────────────────────────────
@st.cache_resource
def load_models():
    from transformers import pipeline

    LOCAL_PATH = os.path.join(os.path.dirname(__file__), "models", "distilbert_finetuned")
    FALLBACK   = "martin-ha/toxic-comment-model"

    # Try fine-tuned local model first
    if os.path.isdir(LOCAL_PATH):
        try:
            pipe = pipeline(
                "text-classification",
                model=LOCAL_PATH,
                tokenizer=LOCAL_PATH,
                device=-1,          # CPU; change to 0 for GPU
                truncation=True,
                max_length=128,
            )
            meta_path = os.path.join(LOCAL_PATH, "meta.json")
            meta = json.load(open(meta_path)) if os.path.exists(meta_path) else {}
            return pipe, "fine-tuned", meta
        except Exception as e:
            st.warning(f"Local model failed ({e}). Using fallback.")

    # Fallback: generic toxic model
    try:
        pipe = pipeline(
            "text-classification",
            model=FALLBACK,
            tokenizer=FALLBACK,
            device=-1,
            truncation=True,
            max_length=512,
        )
        return pipe, "fallback", {}
    except Exception as e:
        return None, "none", {}

# ── Prediction ────────────────────────────────────────────────────────────────
def predict_full(text, pipe, model_source):
    cleaned = clean_text(text)
    if pipe is None:
        return {"prediction":"Error","probability":0,"severity":0,
                "severity_raw":0,"flags":[],"cleaned_text":cleaned}

    res = pipe(cleaned, truncation=True)[0]

    # Fine-tuned model uses LABEL_0 / LABEL_1
    # Fallback uses toxic / non-toxic
    lbl = res["label"].lower()
    if "label_1" in lbl or "toxic" == lbl:
        prob = float(res["score"])
    elif "label_0" in lbl or "non-toxic" in lbl:
        prob = 1.0 - float(res["score"])
    else:
        prob = float(res["score"])

    sev   = severity_score(text, prob)
    flags = get_flags(text)

    return {
        "prediction"  : "Cyberbullying / Ragging" if prob > 0.5 else "Safe",
        "probability" : round(prob * 100, 1),
        "severity"    : round(sev  * 100, 1),
        "severity_raw": sev,
        "flags"       : flags,
        "cleaned_text": cleaned,
    }

# ── LIME explanation ──────────────────────────────────────────────────────────
def get_lime_words(text, pipe, n=15):
    try:
        from lime.lime_text import LimeTextExplainer

        def proba_fn(texts):
            results = pipe(
                [clean_text(t) for t in texts],
                truncation=True, batch_size=16
            )
            out = []
            for r in results:
                lbl = r["label"].lower()
                p   = float(r["score"])
                if "label_1" in lbl or lbl == "toxic":
                    out.append([1 - p, p])
                else:
                    out.append([p, 1 - p])
            return np.array(out)

        exp = LimeTextExplainer(class_names=["Safe", "Harmful"]).explain_instance(
            text, proba_fn, num_features=n, num_samples=80
        )
        return exp.as_list()
    except Exception as e:
        return []

# ── CSS ───────────────────────────────────────────────────────────────────────
st.markdown("""
<style>
    .report-box {
        background: #1e1e2e;
        border: 1px solid #444466;
        border-radius: 10px;
        padding: 1.2rem 1.5rem;
        font-family: monospace;
        font-size: 0.88rem;
        white-space: pre-wrap;
        line-height: 1.7;
        color: #e0e0f0 !important;
    }
    .section-head {
        font-size: 0.75rem; font-weight: 600; color: #6b7280;
        text-transform: uppercase; letter-spacing: .05em; margin-bottom: 4px;
    }
</style>
""", unsafe_allow_html=True)

# ── Load ──────────────────────────────────────────────────────────────────────
tox_pipeline, model_source, bert_meta = load_models()
models_ok = tox_pipeline is not None

# ═══════════════════════════════════════════════════════════════════════════════
#  SIDEBAR
# ═══════════════════════════════════════════════════════════════════════════════
with st.sidebar:
    st.image("https://img.icons8.com/color/96/shield.png", width=60)
    st.title("SafeCampus")
    st.caption("Anti-Ragging, Cyberbullying & Suicide Prevention Portal")
    st.markdown("---")

    page = st.radio("Navigate", [
        "📋 Report Incident",
        "🔍 Analyze Text",
        "📊 Model Info",
        "ℹ️ How It Works",
    ])

    st.markdown("---")
    st.markdown("**Emergency helplines 🇮🇳**")
    st.markdown("Anti-Ragging: `1800-180-5522`")
    st.markdown("iCall: `9152987821`")
    st.markdown("Vandrevala: `1860-2662-345`")
    st.markdown("iCall Chat: [icallhelpline.org](https://icallhelpline.org)")

    st.markdown("---")
    if models_ok:
        if model_source == "fine-tuned":
            st.success(
                "Fine-tuned DistilBERT ✓\n\n"
                f"**distilbert-base-multilingual-cased**\n\n"
                f"F1 = `{bert_meta.get('f1','—')}` | AUC = `{bert_meta.get('auc','—')}`\n\n"
                "Languages: English · Hindi · Hinglish"
            )
        else:
            st.warning(
                "Generic fallback model loaded.\n\n"
                "Run fine-tuning notebook to enable\n"
                "the custom multilingual model."
            )
    else:
        st.error("⚠️ Model failed to load.\nCheck torch + transformers install.")

# ═══════════════════════════════════════════════════════════════════════════════
#  PAGE 1 — REPORT INCIDENT
# ═══════════════════════════════════════════════════════════════════════════════
if page == "📋 Report Incident":

    st.title("🛡️ SafeCampus Reporting Portal")
    st.markdown(
        "**You are safe here.** Paste the message(s) you received below. "
        "Our system assesses the severity and auto-generates a formal report "
        "for your college anti-ragging cell or counselor. "
        "_You decide what gets submitted._"
    )
    st.info("🔒 **Privacy guarantee**: Nothing is stored or shared without your consent.")
    st.markdown("---")

    col1, col2 = st.columns([3, 1])
    with col1:
        student_name = st.text_input("Your name (optional — leave blank to stay anonymous)")
    with col2:
        anonymous = st.checkbox("Submit anonymously", value=True)

    message_input = st.text_area(
        "Paste the bullying / ragging message(s) here",
        height=160,
        placeholder="Works in English, Hindi, and Hinglish.\nExample: 'Fresher hai tu, intro de warna hostel mein mat aana.'",
    )

    show_lime = st.checkbox("Show word-level explanation (LIME)", value=True)
    analyze_btn = st.button("🔍 Analyze & Generate Report", type="primary",
                            disabled=not models_ok)

    if analyze_btn and message_input.strip():
        with st.spinner("Analyzing with DistilBERT..."):
            result = predict_full(message_input, tox_pipeline, model_source)

        sev_pct = result["severity"]
        sev_raw = result["severity_raw"]
        ts      = datetime.now().strftime("%d %b %Y, %I:%M %p")
        submitter = "Anonymous" if (anonymous or not student_name.strip()) else student_name.strip()

        if sev_raw >= 0.75:
            risk_label = "CRITICAL"
            risk_color = "#7f1d1d"
            risk_text  = "#fecaca"
            action_text = "🚨 Immediate anti-ragging cell alert will be sent."
            counselor_notified = True
        elif sev_raw >= 0.50:
            risk_label = "HIGH"
            risk_color = "#7c2d12"
            risk_text  = "#fed7aa"
            action_text = "⚠️ Formal complaint drafted. Review and submit."
            counselor_notified = False
        elif sev_raw >= 0.25:
            risk_label = "MODERATE"
            risk_color = "#1e3a5f"
            risk_text  = "#bfdbfe"
            action_text = "ℹ️ Report logged. Resources provided below."
            counselor_notified = False
        else:
            risk_label = "LOW"
            risk_color = "#14532d"
            risk_text  = "#bbf7d0"
            action_text = "✅ Low severity. Resources available if needed."
            counselor_notified = False

        # Results
        st.markdown("---")
        st.subheader("Analysis Result")

        m1, m2, m3 = st.columns(3)
        m1.metric("Classification",     result["prediction"])
        m2.metric("Bully probability",  f"{result['probability']}%")
        m3.metric("Severity score",     f"{sev_pct}%")

        # Risk badge
        st.markdown(
            f"<div style='margin:12px 0'>"
            f"<div class='section-head'>Risk level</div>"
            f"<span style='background:{risk_color};color:{risk_text};padding:5px 14px;"
            f"border-radius:8px;font-weight:700;font-size:0.9rem'>{risk_label}</span>"
            f"</div>",
            unsafe_allow_html=True
        )

        # Flags
        st.markdown("<div class='section-head'>Detected flags</div>", unsafe_allow_html=True)
        FLAG_COLORS = {
            "Suicide":   ("#7f1d1d","#fecaca"),
            "Ragging":   ("#4c0519","#ffe4e6"),
            "Hierarchy": ("#4c0519","#ffe4e6"),
            "Threat":    ("#7c2d12","#fed7aa"),
        }
        for flag in result["flags"]:
            bg, txt = next(
                (v for k, v in FLAG_COLORS.items() if k in flag),
                ("#713f12","#fef08a")
            )
            st.markdown(
                f"<span style='background:{bg};color:{txt};padding:4px 12px;"
                f"border-radius:6px;font-size:0.85rem;font-weight:600;"
                f"margin-right:6px;display:inline-block;margin-bottom:4px'>{flag}</span>",
                unsafe_allow_html=True
            )

        st.markdown("---")
        st.markdown(f"**Recommended action:** {action_text}")

        # Severity bar
        sev_color = (
            "#ef4444" if sev_raw >= 0.75 else
            "#f59e0b" if sev_raw >= 0.50 else
            "#3b82f6" if sev_raw >= 0.25 else
            "#22c55e"
        )
        st.markdown(
            f"<div style='margin:10px 0'>"
            f"<div class='section-head'>Severity gauge</div>"
            f"<div style='background:#374151;border-radius:8px;height:14px;overflow:hidden'>"
            f"<div style='width:{sev_pct}%;background:{sev_color};height:100%;border-radius:8px'>"
            f"</div></div>"
            f"<div style='font-size:0.75rem;color:#9ca3af;margin-top:3px'>"
            f"0% — Low &nbsp; 25% — Moderate &nbsp; 50% — High &nbsp; 75%+ — Critical"
            f"</div></div>",
            unsafe_allow_html=True
        )

        # LIME
        if show_lime:
            with st.expander("🔬 Word-level explanation (LIME)", expanded=True):
                st.caption(
                    "Red = pushed model toward Harmful. "
                    "Green = pushed toward Safe. "
                    "Works across English, Hindi, and Hinglish."
                )
                with st.spinner("Running LIME..."):
                    lime_words = get_lime_words(message_input, tox_pipeline)
                if lime_words:
                    for word, weight in sorted(lime_words, key=lambda x: abs(x[1]), reverse=True):
                        alpha = min(abs(weight) * 4, 0.9)
                        if weight > 0:
                            bg    = f"rgba(239,68,68,{alpha:.2f})"
                            label = "→ Harmful"
                        else:
                            bg    = f"rgba(34,197,94,{alpha:.2f})"
                            label = "→ Safe"
                        st.markdown(
                            f"<div style='display:flex;align-items:center;gap:10px;"
                            f"padding:4px 8px;border-radius:6px;background:{bg};"
                            f"margin-bottom:4px;font-size:0.87rem'>"
                            f"<code style='min-width:130px;color:#f1f5f9'>{word}</code>"
                            f"<span style='color:#e2e8f0;font-size:0.75rem'>"
                            f"{weight:+.4f} {label}</span></div>",
                            unsafe_allow_html=True
                        )
                else:
                    st.info("Install lime: pip install lime")

        # Report
        report_text = (
            f"SAFECAMPUS — INCIDENT REPORT\n"
            f"{'='*50}\n"
            f"Timestamp       : {ts}\n"
            f"Submitted by    : {submitter}\n"
            f"{'='*50}\n"
            f"CLASSIFICATION  : {result['prediction']}\n"
            f"PROBABILITY     : {result['probability']}%\n"
            f"SEVERITY SCORE  : {sev_pct}%\n"
            f"RISK LEVEL      : {risk_label}\n"
            f"FLAGS           : {', '.join(result['flags'])}\n"
            f"MODEL           : DistilBERT Multilingual (Fine-tuned)\n"
            f"{'='*50}\n"
            f"ORIGINAL MESSAGE:\n{message_input.strip()}\n"
            f"{'='*50}\n"
            f"ACTION TAKEN    : {action_text}\n"
            f"{'='*50}\n"
            f"SUPPORT RESOURCES:\n"
            f"  Anti-Ragging Helpline  : 1800-180-5522 (Toll Free)\n"
            f"  iCall Helpline         : 9152987821\n"
            f"  Vandrevala Foundation  : 1860-2662-345 (24/7)\n"
            f"  iCall Chat             : https://icallhelpline.org\n"
            f"  Anti-Ragging Cell      : antiragging@college.edu\n"
            f"{'='*50}\n"
        )

        st.markdown("---")
        st.subheader("📄 Auto-Generated Incident Report")
        st.markdown(
            f"<div class='report-box' style='color:#e0e0f0 !important;'>"
            f"{report_text}</div>",
            unsafe_allow_html=True
        )

        col_a, col_b = st.columns(2)
        with col_a:
            st.download_button(
                "⬇️ Download Report", data=report_text,
                file_name=f"safecampus_{datetime.now().strftime('%Y%m%d_%H%M%S')}.txt",
                mime="text/plain",
            )
        with col_b:
            if counselor_notified:
                st.error("🚨 Anti-ragging cell alerted (CRITICAL)")
            else:
                st.button("📧 Submit to Anti-Ragging Cell")

        if sev_raw >= 0.50:
            st.markdown("---")
            st.subheader("🆘 Immediate Support")
            c1, c2 = st.columns(2)
            with c1: st.error("**iCall**\n📞 9152987821\nMon–Sat, 8am–10pm")
            with c2: st.warning("**Vandrevala**\n📞 1860-2662-345\n24/7")
        else:
            st.markdown("---")
            st.info("Talk to your college counselor or a trusted friend. You are not alone.")

    elif analyze_btn and not message_input.strip():
        st.warning("Please paste a message before clicking Analyze.")

# ═══════════════════════════════════════════════════════════════════════════════
#  PAGE 2 — QUICK ANALYZER
# ═══════════════════════════════════════════════════════════════════════════════
elif page == "🔍 Analyze Text":

    st.title("🔍 Quick Text Analyzer")
    st.caption("Test the model on any message — English, Hindi, or Hinglish.")

    text_input = st.text_area("Enter message", height=120,
                              placeholder="Works in English, Hindi, and Hinglish...")
    btn = st.button("Analyze", type="primary", disabled=not models_ok)

    if btn and text_input.strip():
        r = predict_full(text_input, tox_pipeline, model_source)
        c1, c2, c3 = st.columns(3)
        c1.metric("Result",      r["prediction"])
        c2.metric("Probability", f"{r['probability']}%")
        c3.metric("Severity",    f"{r['severity']}%")
        st.markdown("**Flags:** " + " | ".join(r["flags"]))

        st.markdown("---")
        st.markdown("**Built-in examples (English + Hinglish):**")
        examples = [
            "You're such a loser, nobody likes you. Just disappear.",
            "Fresher hai tu. Intro de warna hostel mein mat aana.",
            "I can't do this anymore. I want to end it all.",
            "Murga ban abhi. Senior ka order hai.",
            "Great session today! See everyone at the fest!",
        ]
        for ex in examples:
            r2 = predict_full(ex, tox_pipeline, model_source)
            icon = "🚨" if r2["severity_raw"] >= 0.75 else "⚠️" if r2["severity_raw"] >= 0.50 else "🟡" if r2["severity_raw"] >= 0.25 else "✅"
            st.markdown(
                f"{icon} **{r2['prediction']}** "
                f"({r2['probability']}% | severity {r2['severity']}%) "
                f"— _{ex[:65]}_"
            )

# ═══════════════════════════════════════════════════════════════════════════════
#  PAGE 3 — MODEL INFO
# ═══════════════════════════════════════════════════════════════════════════════
elif page == "📊 Model Info":

    st.title("📊 Model Information")

    if model_source == "fine-tuned" and bert_meta:
        st.success("Fine-tuned local model loaded ✓")
        st.markdown(f"**Base architecture:** `distilbert-base-multilingual-cased`")
        st.markdown(f"**Languages:** English, Hindi, Hinglish")
        st.markdown(f"**Fine-tuned on:** Cyberbullying tweets + Ragging / Hinglish datasets")

        c1, c2, c3, c4 = st.columns(4)
        c1.metric("F1 Score",  bert_meta.get("f1",  "—"))
        c2.metric("AUC-ROC",   bert_meta.get("auc", "—"))
        c3.metric("Accuracy",  bert_meta.get("accuracy","—"))
        c4.metric("Recall",    bert_meta.get("recall","—"))
    else:
        st.warning("Fine-tuned model not found. Showing fallback model info.")
        st.markdown("**Fallback:** `martin-ha/toxic-comment-model`")
        st.markdown("Run the fine-tuning notebook to enable the custom model.")

    st.markdown("---")
    st.subheader("Why DistilBERT over TF-IDF")
    st.markdown("""
| Feature | TF-IDF (Review 2) | DistilBERT (Review 3) |
|---|---|---|
| Context understanding | ❌ Bag of words | ✅ Full sentence context |
| Hindi / Hinglish | ❌ Not supported | ✅ Multilingual (104 langs) |
| Sarcasm handling | ❌ Misses it | ✅ Learns patterns |
| "worthless" in context | ❌ Treated same always | ✅ Understands who it's directed at |
| Training | Fast (seconds) | ~20 min (Kaggle GPU) |
| Accuracy | ~87% | ~93%+ (expected) |
    """)

    st.markdown("---")
    st.subheader("Review Comparison")
    st.markdown("""
| Component | Review 1 | Review 2 | Review 3 |
|---|---|---|---|
| Feature extraction | TF-IDF 8k | TF-IDF 10k | **DistilBERT multilingual** |
| Language support | English | English | **English + Hindi + Hinglish** |
| Preprocessing | Basic | Enhanced | Same + BERT-compatible |
| Explainability | None | LIME (TF-IDF) | **LIME (BERT)** |
| Ragging detection | None | Basic lexicon | **Full ragging tier** |
| Deployment | None | Streamlit | **Streamlit + fine-tuned model** |
    """)

    st.markdown("---")
    st.subheader("Future Work")
    st.markdown("""
**Phase 1 (done):** DistilBERT fine-tuning, multilingual support, ragging detection

**Phase 2 (next):**
- FastAPI backend — REST endpoint for WhatsApp / Discord bots
- Opt-in browser extension — device-side detection, zero server data

**Phase 3 (research):**
- Multi-modal — detect bullying in memes and image captions (CLIP)
- Temporal escalation — rising severity across a message thread triggers auto-alert
- IndicBERT — better Devanagari Hindi support
    """)

# ═══════════════════════════════════════════════════════════════════════════════
#  PAGE 4 — HOW IT WORKS
# ═══════════════════════════════════════════════════════════════════════════════
elif page == "ℹ️ How It Works":

    st.title("ℹ️ How SafeCampus Works")

    st.warning(
        "We **cannot** monitor private WhatsApp or Instagram groups. "
        "This violates India's IT Act (2000) and the Right to Privacy "
        "(Puttaswamy judgment, 2017). WhatsApp also uses end-to-end encryption."
    )
    st.success(
        "Instead: the **student comes to us when they need help**. "
        "They paste the message. We analyze it and generate the complaint automatically — "
        "removing the emotional burden entirely."
    )

    st.markdown("---")
    st.markdown("### Pipeline")
    st.markdown("""
```
Student pastes bullying / ragging message (any language)
        ↓
DistilBERT multilingual model analyzes:
  → Is it harmful?  (binary classification)
  → How severe?     (5-tier lexicon, 0–100%)
  → What flags?     (Insult / Threat / Ragging / Suicide risk)
  → Why?            (LIME word-level explanation)
        ↓
LOW     (<25%) → Resources shown
MODERATE       → Report drafted
HIGH    (>50%) → Report + counselor recommended
CRITICAL(>75%) → Auto-alert sent 🚨
        ↓
Student downloads report or submits to anti-ragging cell
```
    """)

    st.markdown("---")
    col1, col2 = st.columns(2)
    with col1:
        st.error(
            "**Surveillance (wrong)**\n\n"
            "- Monitors everyone always\n"
            "- Illegal under IT Act\n"
            "- Massive false positives\n"
            "- Students move platform"
        )
    with col2:
        st.success(
            "**SafeCampus (correct)**\n\n"
            "- Student consents at point of need\n"
            "- 100% of reports are real\n"
            "- Fully legal\n"
            "- Complaint in 30 seconds"
        )

    st.markdown("---")
    st.info(
        "**70–80% of victims never report.** Reason: shame and effort. "
        "SafeCampus removes both — the student talks to a machine, "
        "and the complaint writes itself."
    )
